const pre = 'nhlpoolhelper/auth/';

export default {
  LOGIN_REQUEST: `${pre}LOGIN_REQUEST`,
  LOGIN_SUCCESS: `${pre}LOGIN_SUCCESS`,
  LOGIN_FAILURE: `${pre}LOGIN_FAILURE`,

  REGISTER_REQUEST: `${pre}REGISTER_REQUEST`,
  REGISTER_SUCCESS: `${pre}REGISTER_SUCCESS`,
  REGISTER_FAILURE: `${pre}REGISTER_FAILURE`,

  LOAD_PROFILE_SUCCESS: `${pre}LOAD_PROFILE_SUCCESS`,
  LOAD_PROFILE_UNAUTHORIZED: `${pre}LOAD_PROFILE_UNAUTHORIZED`,

  LOGOUT_SUCCESS: `${pre}LOGOUT_SUCCESS`,
};
